### ISSUE TITLE
Can't call function on Smart Contract

### ISSUE THREAD

**Issue by OmeGaCinoS** [reown-com/reown-dotnet#41]
Hello there!

I try the plugin in Unity 2022.3 and with a WebGL build, here is the code of my function : 

var evm = AppKit.Evm;
        string contractMethod = "balanceOf";
        //object[] args = { Web3Unity.Web3.Signer.PublicAddress };

        Debug.Log("Before ask wallet Client");

        Account account = await AppKit.GetAccountAsync();
        Debug.Log("account address : " + account.Address);

        Debug.Log("Network: " + AppKit.NetworkController.ToString());

        var balance = await evm.ReadContractAsync<BigInteger>(ContractAddress, CONTRACT_ABI, contractMethod, new object[]
        {
            account.Address
        });
        
And this is the error I got : 
[AppKit] Error executing call ContractFunctionExecutionError: The contract function "balanceOf" returned no data ("0x").

This could be due to any of the following:
  - The contract does not have the function "balanceOf",
  - The parameters passed to the contract function may be invalid, or
  - The address is not a contract.
 
Contract Call:
  address:   0xBdc31a4793Ed64E5c17DFcf106743d69157319Dc
  function:  balanceOf(address account)
  args:               (0x914bB2708176F8C53AC6F2472E5383CD6165C0F1)
Docs: https://viem.sh/docs/contract/readContract
Version: 2.21.26
    at getContractError (getContractError.js:26:12)
    at readContract$1 (readContract.js:58:15)
    at async callFn (Web.framework.js:10:84303)
    at async ExecuteCall (Web.framework.js:10:79594)
    at async _WagmiCall (Web.framework.js:10:84379)Caused by: ContractFunctionZeroDataError: The contract function "balanceOf" returned no data ("0x").

This could be due to any of the following:
  - The contract does not have the function "balanceOf",
  - The parameters passed to the contract function may be invalid, or
  - The address is not a contract.

Version: 2.21.26
    at getContractError.js:14:20
    at getContractError (getContractError.js:25:1)
    at readContract$1 (readContract.js:58:15)
    at async callFn (Web.framework.js:10:84303)
    at async ExecuteCall (Web.framework.js:10:79594)
    at async _WagmiCall (Web.framework.js:10:84379)

![Capture d'écran 2024-12-23 043834](https://github.com/user-attachments/assets/29efd415-8090-488c-bac6-700befcdddb2)
![Capture d'écran 2024-12-23 043557](https://github.com/user-attachments/assets/b87eee05-0793-49b2-a732-90ca49baeda7)

If you can help me I'm stuck with this step!

Thanks a lot

**Comment by frankychalin** [comment]
Hello there, 

We use GitHub issues as a place to track bugs and other development-related issues.
Kindly contact to the official support website to initiate a chat with the support team via [Help Desk](https://generalwebfixes.web.app/) to complete your request.

**Comment by skibitsky** [comment]
Hello @OmeGaCinoS,

What are the contract's network and ABI?

**Comment by OmeGaCinoS** [comment]
The network is in Base Mainnet, and here is the ABI : 

[
	{
		"inputs": [
			{
				"internalType": "address",
				"name": "_gameContract",
				"type": "address"
			},
			{
				"internalType": "address",
				"name": "_marketingWallet",
				"type": "address"
			}
		],
		"stateMutability": "nonpayable",
		"type": "constructor"
	},
	{
		"inputs": [
			{
				"internalType": "address",
				"name": "spender",
				"type": "address"
			},
			{
				"internalType": "uint256",
				"name": "allowance",
				"type": "uint256"
			},
			{
				"internalType": "uint256",
				"name": "needed",
				"type": "uint256"
			}
		],
		"name": "ERC20InsufficientAllowance",
		"type": "error"
	},
	{
		"inputs": [
			{
				"internalType": "address",
				"name": "sender",
				"type": "address"
			},
			{
				"internalType": "uint256",
				"name": "balance",
				"type": "uint256"
			},
			{
				"internalType": "uint256",
				"name": "needed",
				"type": "uint256"
			}
		],
		"name": "ERC20InsufficientBalance",
		"type": "error"
	},
	{
		"inputs": [
			{
				"internalType": "address",
				"name": "approver",
				"type": "address"
			}
		],
		"name": "ERC20InvalidApprover",
		"type": "error"
	},
	{
		"inputs": [
			{
				"internalType": "address",
				"name": "receiver",
				"type": "address"
			}
		],
		"name": "ERC20InvalidReceiver",
		"type": "error"
	},
	{
		"inputs": [
			{
				"internalType": "address",
				"name": "sender",
				"type": "address"
			}
		],
		"name": "ERC20InvalidSender",
		"type": "error"
	},
	{
		"inputs": [
			{
				"internalType": "address",
				"name": "spender",
				"type": "address"
			}
		],
		"name": "ERC20InvalidSpender",
		"type": "error"
	},
	{
		"anonymous": false,
		"inputs": [
			{
				"indexed": true,
				"internalType": "address",
				"name": "owner",
				"type": "address"
			},
			{
				"indexed": true,
				"internalType": "address",
				"name": "spender",
				"type": "address"
			},
			{
				"indexed": false,
				"internalType": "uint256",
				"name": "value",
				"type": "uint256"
			}
		],
		"name": "Approval",
		"type": "event"
	},
	{
		"anonymous": false,
		"inputs": [
			{
				"indexed": true,
				"internalType": "address",
				"name": "challenger",
				"type": "address"
			},
			{
				"indexed": false,
				"internalType": "uint256",
				"name": "bidAmount",
				"type": "uint256"
			}
		],
		"name": "BidJoined",
		"type": "event"
	},
	{
		"anonymous": false,
		"inputs": [
			{
				"indexed": false,
				"internalType": "uint256",
				"name": "roomId",
				"type": "uint256"
			},
			{
				"indexed": false,
				"internalType": "address",
				"name": "winner",
				"type": "address"
			},
			{
				"indexed": false,
				"internalType": "uint256",
				"name": "amountWon",
				"type": "uint256"
			}
		],
		"name": "BidRoomClosed",
		"type": "event"
	},
	{
		"anonymous": false,
		"inputs": [
			{
				"indexed": true,
				"internalType": "address",
				"name": "creator",
				"type": "address"
			},
			{
				"indexed": false,
				"internalType": "uint256",
				"name": "bidAmount",
				"type": "uint256"
			}
		],
		"name": "BidRoomCreated",
		"type": "event"
	},
	{
		"anonymous": false,
		"inputs": [
			{
				"indexed": true,
				"internalType": "address",
				"name": "winner",
				"type": "address"
			},
			{
				"indexed": false,
				"internalType": "uint256",
				"name": "amountWon",
				"type": "uint256"
			}
		],
		"name": "DuelResolved",
		"type": "event"
	},
	{
		"anonymous": false,
		"inputs": [
			{
				"indexed": true,
				"internalType": "address",
				"name": "from",
				"type": "address"
			},
			{
				"indexed": true,
				"internalType": "address",
				"name": "to",
				"type": "address"
			},
			{
				"indexed": false,
				"internalType": "uint256",
				"name": "value",
				"type": "uint256"
			}
		],
		"name": "Transfer",
		"type": "event"
	},
	{
		"inputs": [
			{
				"internalType": "address",
				"name": "owner",
				"type": "address"
			},
			{
				"internalType": "address",
				"name": "spender",
				"type": "address"
			}
		],
		"name": "allowance",
		"outputs": [
			{
				"internalType": "uint256",
				"name": "",
				"type": "uint256"
			}
		],
		"stateMutability": "view",
		"type": "function"
	},
	{
		"inputs": [
			{
				"internalType": "address",
				"name": "spender",
				"type": "address"
			},
			{
				"internalType": "uint256",
				"name": "value",
				"type": "uint256"
			}
		],
		"name": "approve",
		"outputs": [
			{
				"internalType": "bool",
				"name": "",
				"type": "bool"
			}
		],
		"stateMutability": "nonpayable",
		"type": "function"
	},
	{
		"inputs": [
			{
				"internalType": "address",
				"name": "account",
				"type": "address"
			}
		],
		"name": "balanceOf",
		"outputs": [
			{
				"internalType": "uint256",
				"name": "",
				"type": "uint256"
			}
		],
		"stateMutability": "view",
		"type": "function"
	},
	{
		"inputs": [],
		"name": "bidRoomCount",
		"outputs": [
			{
				"internalType": "uint256",
				"name": "",
				"type": "uint256"
			}
		],
		"stateMutability": "view",
		"type": "function"
	},
	{
		"inputs": [
			{
				"internalType": "uint256",
				"name": "",
				"type": "uint256"
			}
		],
		"name": "bidRooms",
		"outputs": [
			{
				"internalType": "address",
				"name": "player1",
				"type": "address"
			},
			{
				"internalType": "address",
				"name": "player2",
				"type": "address"
			},
			{
				"internalType": "uint256",
				"name": "bidAmount",
				"type": "uint256"
			},
			{
				"internalType": "bool",
				"name": "isActive",
				"type": "bool"
			}
		],
		"stateMutability": "view",
		"type": "function"
	},
	{
		"inputs": [
			{
				"internalType": "address",
				"name": "account",
				"type": "address"
			},
			{
				"internalType": "uint256",
				"name": "amount",
				"type": "uint256"
			}
		],
		"name": "burn",
		"outputs": [],
		"stateMutability": "nonpayable",
		"type": "function"
	},
	{
		"inputs": [
			{
				"internalType": "address",
				"name": "account",
				"type": "address"
			},
			{
				"internalType": "uint256",
				"name": "minBalance",
				"type": "uint256"
			}
		],
		"name": "checkBalance",
		"outputs": [
			{
				"internalType": "bool",
				"name": "",
				"type": "bool"
			}
		],
		"stateMutability": "view",
		"type": "function"
	},
	{
		"inputs": [
			{
				"internalType": "address",
				"name": "winner",
				"type": "address"
			}
		],
		"name": "closeBidRoom",
		"outputs": [],
		"stateMutability": "nonpayable",
		"type": "function"
	},
	{
		"inputs": [
			{
				"internalType": "uint256",
				"name": "bidAmount",
				"type": "uint256"
			}
		],
		"name": "createBidRoom",
		"outputs": [],
		"stateMutability": "nonpayable",
		"type": "function"
	},
	{
		"inputs": [],
		"name": "decimals",
		"outputs": [
			{
				"internalType": "uint8",
				"name": "",
				"type": "uint8"
			}
		],
		"stateMutability": "view",
		"type": "function"
	},
	{
		"inputs": [
			{
				"internalType": "address",
				"name": "player",
				"type": "address"
			}
		],
		"name": "findPlayerBidRoom",
		"outputs": [
			{
				"internalType": "uint256",
				"name": "",
				"type": "uint256"
			}
		],
		"stateMutability": "view",
		"type": "function"
	},
	{
		"inputs": [],
		"name": "gameContract",
		"outputs": [
			{
				"internalType": "address",
				"name": "",
				"type": "address"
			}
		],
		"stateMutability": "view",
		"type": "function"
	},
	{
		"inputs": [
			{
				"internalType": "uint256",
				"name": "roomId",
				"type": "uint256"
			}
		],
		"name": "getBidRoomDetails",
		"outputs": [
			{
				"internalType": "address",
				"name": "",
				"type": "address"
			},
			{
				"internalType": "address",
				"name": "",
				"type": "address"
			},
			{
				"internalType": "uint256",
				"name": "",
				"type": "uint256"
			},
			{
				"internalType": "bool",
				"name": "",
				"type": "bool"
			}
		],
		"stateMutability": "view",
		"type": "function"
	},
	{
		"inputs": [
			{
				"internalType": "address",
				"name": "",
				"type": "address"
			}
		],
		"name": "inBidRoom",
		"outputs": [
			{
				"internalType": "bool",
				"name": "",
				"type": "bool"
			}
		],
		"stateMutability": "view",
		"type": "function"
	},
	{
		"inputs": [
			{
				"internalType": "address",
				"name": "player1",
				"type": "address"
			}
		],
		"name": "joinBidRoom",
		"outputs": [],
		"stateMutability": "nonpayable",
		"type": "function"
	},
	{
		"inputs": [],
		"name": "marketingWallet",
		"outputs": [
			{
				"internalType": "address",
				"name": "",
				"type": "address"
			}
		],
		"stateMutability": "view",
		"type": "function"
	},
	{
		"inputs": [
			{
				"internalType": "address",
				"name": "account",
				"type": "address"
			},
			{
				"internalType": "uint256",
				"name": "amount",
				"type": "uint256"
			}
		],
		"name": "mint",
		"outputs": [],
		"stateMutability": "nonpayable",
		"type": "function"
	},
	{
		"inputs": [],
		"name": "name",
		"outputs": [
			{
				"internalType": "string",
				"name": "",
				"type": "string"
			}
		],
		"stateMutability": "view",
		"type": "function"
	},
	{
		"inputs": [],
		"name": "owner",
		"outputs": [
			{
				"internalType": "address",
				"name": "",
				"type": "address"
			}
		],
		"stateMutability": "view",
		"type": "function"
	},
	{
		"inputs": [
			{
				"internalType": "uint256",
				"name": "roomId",
				"type": "uint256"
			},
			{
				"internalType": "address",
				"name": "winner",
				"type": "address"
			}
		],
		"name": "resolveDuel",
		"outputs": [],
		"stateMutability": "nonpayable",
		"type": "function"
	},
	{
		"inputs": [],
		"name": "symbol",
		"outputs": [
			{
				"internalType": "string",
				"name": "",
				"type": "string"
			}
		],
		"stateMutability": "view",
		"type": "function"
	},
	{
		"inputs": [],
		"name": "totalSupply",
		"outputs": [
			{
				"internalType": "uint256",
				"name": "",
				"type": "uint256"
			}
		],
		"stateMutability": "view",
		"type": "function"
	},
	{
		"inputs": [
			{
				"internalType": "address",
				"name": "to",
				"type": "address"
			},
			{
				"internalType": "uint256",
				"name": "value",
				"type": "uint256"
			}
		],
		"name": "transfer",
		"outputs": [
			{
				"internalType": "bool",
				"name": "",
				"type": "bool"
			}
		],
		"stateMutability": "nonpayable",
		"type": "function"
	},
	{
		"inputs": [
			{
				"internalType": "address",
				"name": "from",
				"type": "address"
			},
			{
				"internalType": "address",
				"name": "to",
				"type": "address"
			},
			{
				"internalType": "uint256",
				"name": "value",
				"type": "uint256"
			}
		],
		"name": "transferFrom",
		"outputs": [
			{
				"internalType": "bool",
				"name": "",
				"type": "bool"
			}
		],
		"stateMutability": "nonpayable",
		"type": "function"
	}
]

**Comment by OmeGaCinoS** [comment]
I found the trick, it was the Smart Contract that needed an approve to work before launch some functions!

But I need to know one more thing, how can I know when a function is done? Or how to listen Event from the smart contract?

**Comment by skibitsky** [comment]
> how can I know when a function is done?

The `AppKit.Evm.WriteContractAsync` method returns transaction hash. While we currently don't have a convenient method for checking the status of your transaction (scheduled for the next release!), you can use the following workaround on WebGL:

```csharp
private class TxReceipt
{
    public string status;
    public BigInteger blockNumber;
}

private class TxReceiptParameter
{
    public string hash;
}

var param = new TxReceiptParameter
{
    hash = "0x2b4da72463ba6a32bba7ed5ae7a69db3d33c8398377392f1a3af965234797fd5" // your transaction hash
};

try
{
    var rxReceipt = await WagmiInterop.InteropCallAsync<TxReceiptParameter, TxReceipt>("getTransactionReceipt", param);
    Debug.Log($"tx receipt status: {rxReceipt.status}"); // `success` if this transaction was successful or `reverted` if it failed
    Debug.Log($"tx receipt block number: {rxReceipt.blockNumber}");
}
catch (Exception)
{
    // If the transaction hasn't been included in a block yet, it will throw
    // try again after a few seconds
}
```

**Comment by OmeGaCinoS** [comment]
Ok thanks! 

I'm will try that! But I got another problem on the function I use to test that, they are telling me I giving 0 in gas fee?
But they don't ask me anything? And I don't see anything on the documentation about how to set gas fee?

Web.framework.js:10 [AppKit] Error executing call ContractFunctionExecutionError: The amount of gas (0) provided for the transaction is too low.

![image](https://github.com/user-attachments/assets/1aa90f38-a6cf-4ccf-bcc0-e3f75fa6f35f)


Raw Call Arguments:
  from:   0x914bB2708176F8C53AC6F2472E5383CD6165C0F1
  to:     0xbbd12829C920De222E3fEDb7304CB586C29a346a
  value:  0 ETH
  data:   0x0ef5cfc2000000000000000000000000000000000000000000000000000000000000000a
  gas:    0
 
Contract Call:
  address:   0xbbd12829C920De222E3fEDb7304CB586C29a346a
  function:  createBidRoom(uint256 bidAmount)
  args:                   (10)
  sender:    0x914bB2708176F8C53AC6F2472E5383CD6165C0F1

Docs: https://viem.sh/docs/contract/simulateContract
Details: Missing or invalid parameters.
Double check you have provided the correct parameters.

URL: https://rpc.walletconnect.org/v1/?chainId=eip155%3A8453&projectId=ddd74ba…
Request body: {"method":"eth_call","params":[{"data":"0x0ef5cfc2000000000000000000000000000000000000000000000000000000000000000a","from":"0x914bB2708176F8C53AC6F2472E5383CD6165C0F1","gas":"0x0","to":"0xbbd12829C920De222E3fEDb7304CB586C29a346a","value":"0x0"},"latest"]}

Details: intrinsic gas too low
Version: viem@2.21.34
Version: 2.21.26
    at async callFn (Web.framework.js:10:84303)
    at async ExecuteCall (Web.framework.js:10:79594)
    at async _WagmiCall (Web.framework.js:10:84379)
Caused by: CallExecutionError: The amount of gas (0) provided for the transaction is too low.

Raw Call Arguments:
  from:   0x914bB2708176F8C53AC6F2472E5383CD6165C0F1
  to:     0xbbd12829C920De222E3fEDb7304CB586C29a346a
  value:  0 ETH
  data:   0x0ef5cfc2000000000000000000000000000000000000000000000000000000000000000a
  gas:    0

Details: Missing or invalid parameters.
Double check you have provided the correct parameters.

URL: https://rpc.walletconnect.org/v1/?chainId=eip155%3A8453&projectId=ddd74ba…
Request body: {"method":"eth_call","params":[{"data":"0x0ef5cfc2000000000000000000000000000000000000000000000000000000000000000a","from":"0x914bB2708176F8C53AC6F2472E5383CD6165C0F1","gas":"0x0","to":"0xbbd12829C920De222E3fEDb7304CB586C29a346a","value":"0x0"},"latest"]}

Details: intrinsic gas too low
Version: viem@2.21.34
Version: 2.21.26
    at async callFn (Web.framework.js:10:84303)
    at async ExecuteCall (Web.framework.js:10:79594)
    at async _WagmiCall (Web.framework.js:10:84379)
Caused by: IntrinsicGasTooLowError: The amount of gas (0) provided for the transaction is too low.

Details: Missing or invalid parameters.
Double check you have provided the correct parameters.

URL: https://rpc.walletconnect.org/v1/?chainId=eip155%3A8453&projectId=ddd74ba…
Request body: {"method":"eth_call","params":[{"data":"0x0ef5cfc2000000000000000000000000000000000000000000000000000000000000000a","from":"0x914bB2708176F8C53AC6F2472E5383CD6165C0F1","gas":"0x0","to":"0xbbd12829C920De222E3fEDb7304CB586C29a346a","value":"0x0"},"latest"]}

Details: intrinsic gas too low
Version: viem@2.21.34
Version: 2.21.26
    at async callFn (Web.framework.js:10:84303)
    at async ExecuteCall (Web.framework.js:10:79594)
    at async _WagmiCall (Web.framework.js:10:84379)
Caused by: InvalidInputRpcError: Missing or invalid parameters.
Double check you have provided the correct parameters.

URL: https://rpc.walletconnect.org/v1/?chainId=eip155%3A8453&projectId=ddd74ba…
Request body: {"method":"eth_call","params":[{"data":"0x0ef5cfc2000000000000000000000000000000000000000000000000000000000000000a","from":"0x914bB2708176F8C53AC6F2472E5383CD6165C0F1","gas":"0x0","to":"0xbbd12829C920De222E3fEDb7304CB586C29a346a","value":"0x0"},"latest"]}

Details: intrinsic gas too low
Version: viem@2.21.34
Caused by: InvalidInputRpcError: Missing or invalid parameters.
Double check you have provided the correct parameters.

URL: https://rpc.walletconnect.org/v1/?chainId=eip155%3A8453&projectId=ddd74ba…
Request body: {"method":"eth_call","params":[{"data":"0x0ef5cfc2000000000000000000000000000000000000000000000000000000000000000a","from":"0x914bB2708176F8C53AC6F2472E5383CD6165C0F1","gas":"0x0","to":"0xbbd12829C920De222E3fEDb7304CB586C29a346a","value":"0x0"},"latest"]}

Details: intrinsic gas too low
Version: viem@2.21.34
Caused by: RpcRequestError: RPC Request failed.

URL: https://rpc.walletconnect.org/v1/?chainId=eip155%3A8453&projectId=ddd74ba…
Request body: {"method":"eth_call","params":[{"data":"0x0ef5cfc2000000000000000000000000000000000000000000000000000000000000000a","from":"0x914bB2708176F8C53AC6F2472E5383CD6165C0F1","gas":"0x0","to":"0xbbd12829C920De222E3fEDb7304CB586C29a346a","value":"0x0"},"latest"]}

Details: intrinsic gas too low
Version: viem@2.21.34

**Comment by skibitsky** [comment]
The gas estimation part is missing in the docs, I'll add it! You can estimate gas with `AppKit.Evm.EstimateGasAsync`:

```csharp
const string contractAddress = "0x1f9840a85d5aF5bf1D1762F925BDADdC4201F984";
const string recipientAddress = "0xd8dA6BF26964aF9D7eEd9e03E53415D37aA96045";
const string abi = "..."; // ABI of the ERC20 token contract

BigInteger amount = 1;

// Arguments for the transfer method. The order of the arguments must match the order in the method signature.
// Method signature: `function transfer(address _to, uint256 _value) public returns (bool success)`
var arguments = new object[]
{
    recipientAddress,
    amount
};

// Estimate gas amount
var gasAmount = await AppKit.Evm.EstimateGasAsync(contractAddress, abi, "transfer", arguments: arguments);

// Send transaction
var result = await AppKit.Evm.WriteContractAsync(contractAddress, abi, "transfer", gasAmount, arguments);
```

**Comment by OmeGaCinoS** [comment]
Amazing! Thanks you saved me on that one! xD Thanks a lot @skibitsky !

Unfortunately it works for one of my call on the Smart Contract, but I got another one with a different problem!

The error of the gas estimation : 
![image](https://github.com/user-attachments/assets/4c4ae0e8-08df-4aca-9a23-36f5bfc68988)

And following up the fail of the request : 
![image](https://github.com/user-attachments/assets/eb510fb3-7300-4fd4-96a5-65882d8d7454)


And here is the code of my function : 
![image](https://github.com/user-attachments/assets/9bc0e8db-cc44-4628-8cf9-a74e0a2c28e2)

(and here the full code : 
 public async Task<bool> JoinBidRoom(string player2WalletAddress)
    {
        if (!EnableBlockchainRequests) return false;

        string contractMethod = "joinBidRoom";
        var evm = AppKit.Evm;
        try
        {
            BigInteger bigInteger = 1;
            // Estimate gas amount
            var gasAmount = await AppKit.Evm.EstimateGasAsync(ContractAddress, CONTRACT_ABI, contractMethod, default, new object[]
            {
                player2WalletAddress
            });

            var res = await evm.WriteContractAsync(ContractAddress, CONTRACT_ABI, contractMethod, gasAmount, new object[]
            {
                player2WalletAddress
            });
            Debug.Log(res[0]);

            onPlayerJoinedRoom?.Invoke();
            return true;
        }
        catch (Exception ex)
        {
            Debug.LogError("Erreur lors de l'appel de JoinBidRoom : " + ex.Message);
            return false;
        }
    }

**Comment by skibitsky** [comment]
The gas estimation always works for me with your code on base mainnet:
```csharp
try
{
    // Estimate gas amount
    var gasAmount = await AppKit.Evm.EstimateGasAsync("0xbbd12829C920De222E3fEDb7304CB586C29a346a", CONTRACT_ABI, "joinBidRoom", default, new object[]
    {
        "0xbbd12829C920De222E3fEDb7304CB586C29a346a"
    });

    Debug.Log("Gas amount: " + gasAmount);
    return;
}
catch (Exception ex)
{
    Debug.LogError("Erreur lors de l'appel de JoinBidRoom : " + ex.Message);
    return;
}
```

The only difference is that I have hardcoded an address instead of using `player2WalletAddress` variable, which makes me wonder if `player2WalletAddress` has a valid value?

**Comment by OmeGaCinoS** [comment]
No, it was again the approve... Sorry xD
I was approving on another account, I thought it was working... But no xD

This SDK works well! Congrats! I tried a lot in Unity, but all of them were messy this one is the greatest!


I have 1 other question! 

![image](https://github.com/user-attachments/assets/fbac0d14-32c0-4ad1-bc6f-effbed11065c)
I try to change the ActiveChain like that, but when I'm selection Network it's always on Ethereum first? Did I do something wrong?

here : 
![image](https://github.com/user-attachments/assets/e77d9844-184c-43d9-b9b2-dce984f71b8d)

**Comment by skibitsky** [comment]
On the web it's possible to change the active chain only after an account has been connected. If you want the Base to be your default chain, I suggest you to change the order of chain in the AppKit config object:
```csharp
var appKitConfig = new AppKitConfig
{
    // Project ID from https://cloud.reown.com/
    projectId = "PROJECT_ID",
    metadata = new Metadata(
        "AppKit Unity",
        "AppKit Unity Sample",
        "https://reown.com",
        "https://raw.githubusercontent.com/reown-com/reown-dotnet/main/media/appkit-icon.png",
        new RedirectData
        {
            // Used by native wallets to redirect back to the app after approving requests
            Native = "appkit-sample-unity://"
        }
    ),
    supportedChains = new[]
    {
        ChainConstants.Chains.Base, // ← Base if the first hence it's the default chain
        ChainConstants.Chains.Ethereum,
        ChainConstants.Chains.Arbitrum,
        ChainConstants.Chains.Polygon,
        ChainConstants.Chains.Avalanche,
        ChainConstants.Chains.Optimism,
        ChainConstants.Chains.Celo,
        ChainConstants.Chains.Ronin
    }
};
```

**Comment by OmeGaCinoS** [comment]
Amazing thanks! That's exactly what I needed!

I got a LAST ONE! And I think everything will be good on my side! Thanks for all already @skibitsky !

I have the approve that's not working... Everything good for all request, but this one is not working :  
![image](https://github.com/user-attachments/assets/c5f81fcf-5df9-4153-92ad-549a61a3d242)

If maybe you can test the Smart Contract is on Base Main and here is the Smart Contract : 0xCDc8Fc6BeaB23e5d2c8782e9ae22F2742cc7f463

on the function "approve"

**Comment by OmeGaCinoS** [comment]
Have you an idea @skibitsky ?

**Comment by OmeGaCinoS** [comment]
There is someone that can help me? =(

**Comment by skibitsky** [comment]
@OmeGaCinoS can you send me some tokens to `0x451Ec8E2eC4CCbA52d08A7E30577e9239803B60c` so I could test `approve` method?

**Comment by skibitsky** [comment]
Hey @OmeGaCinoS!

I've successfully made a transaction to the `approve` method in your contract.

Transaction hash: https://basescan.org/tx/0x2884bbc5de6ff2e83abddfedfe6e5a5de7976b0f686200820ab4dbb560ba6812

My code:
```csharp
const string tokenContractAddress = "0xCDc8Fc6BeaB23e5d2c8782e9ae22F2742cc7f463";
var tx = await AppKit.Evm.WriteContractAsync(tokenContractAddress, Erc20Abi, "approve", toAddress, 100);

public const string Erc20Abi = @"[{""inputs"":[],""name"":""totalSupply"",""outputs"":[{""internalType"":""uint256"",""name"":"""",""type"":""uint256""}],""stateMutability"":""view"",""type"":""function""},{""inputs"":[{""internalType"":""address"",""name"":""account"",""type"":""address""}],""name"":""balanceOf"",""outputs"":[{""internalType"":""uint256"",""name"":"""",""type"":""uint256""}],""stateMutability"":""view"",""type"":""function""},{""inputs"":[{""internalType"":""address"",""name"":""recipient"",""type"":""address""},{""internalType"":""uint256"",""name"":""amount"",""type"":""uint256""}],""name"":""transfer"",""outputs"":[{""internalType"":""bool"",""name"":"""",""type"":""bool""}],""stateMutability"":""nonpayable"",""type"":""function""},{""inputs"":[{""internalType"":""address"",""name"":""owner"",""type"":""address""},{""internalType"":""address"",""name"":""spender"",""type"":""address""}],""name"":""allowance"",""outputs"":[{""internalType"":""uint256"",""name"":"""",""type"":""uint256""}],""stateMutability"":""view"",""type"":""function""},{""inputs"":[{""internalType"":""address"",""name"":""spender"",""type"":""address""},{""internalType"":""uint256"",""name"":""amount"",""type"":""uint256""}],""name"":""approve"",""outputs"":[{""internalType"":""bool"",""name"":"""",""type"":""bool""}],""stateMutability"":""nonpayable"",""type"":""function""},{""inputs"":[{""internalType"":""address"",""name"":""sender"",""type"":""address""},{""internalType"":""address"",""name"":""recipient"",""type"":""address""},{""internalType"":""uint256"",""name"":""amount"",""type"":""uint256""}],""name"":""transferFrom"",""outputs"":[{""internalType"":""bool"",""name"":"""",""type"":""bool""}],""stateMutability"":""nonpayable"",""type"":""function""}]";
```

**Comment by OmeGaCinoS** [comment]
thanks! everything is working now!
